platform :ios, '9.0'
use_frameworks!

plugin 'cocoapods-acknowledgements'

def common_pods
  pod 'Pantry', git: 'https://github.com/nickoneill/pantry.git', branch: 'nick-file-protection' # needed for app support folder change
  pod 'R.swift'
end

target 'FiveCalls' do
  common_pods
  pod 'OneSignal', '~> 2.5'
  pod 'CPDAcknowledgements'
  pod 'Fabric'
  pod 'Crashlytics', '~> 3.8.4'
  pod 'DZNEmptyDataSet', git: 'https://github.com/subdigital/DZNEmptyDataSet'
end

target 'NotificationsService' do
    pod 'OneSignal', '~> 2.5'
end

target 'FiveCallsTests' do
  common_pods
end

