platform :ios, '10.2'
use_frameworks!

plugin 'cocoapods-acknowledgements'

def common_pods
  pod 'Pantry', git: 'https://github.com/nickoneill/pantry.git', 
    branch: 'nick-file-protection',
    inhibit_warnings: true
  pod 'R.swift', '~> 5.0'
end

target 'FiveCalls' do
  common_pods
  pod 'Auth0', '~> 1.15', inhibit_warnings: true
  pod 'CPDAcknowledgements', git: 'https://github.com/CocoaPods/CPDAcknowledgements.git'
  pod 'Crashlytics', '~> 3.10.7'
  pod 'DZNEmptyDataSet', git: 'https://github.com/subdigital/DZNEmptyDataSet'
  pod 'Fabric'
  pod 'Kingfisher', '~> 4.0'
  pod 'OneSignal', '~> 2.5'
  pod 'PromiseKit', '~> 6.0'
  pod 'Down', inhibit_warnings: true
  pod 'Bugsnag'
  pod 'Mixpanel'
end

target 'NotificationsService' do
    pod 'OneSignal', '~> 2.5'
end

target 'FiveCallsTests' do
  common_pods
end

