
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

fastlane_version "2.14.2"

default_platform :ios

workspace = 'FiveCalls/FiveCalls.xcworkspace'
xcodeproj = 'FiveCalls/FiveCalls.xcodeproj'
scheme = 'FiveCalls'

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    scan(workspace: workspace, scheme: scheme)
  end

  desc "Increments build number"
  lane :increment_build do
    increment_build_number(xcodeproj: xcodeproj)
  end

  lane :app_version do
    get_app_version(xcodeproj: xcodeproj)
  end

  def get_app_version(xcodeproj:)
    marketing_version = get_version_number(xcodeproj: xcodeproj)
    build_number = get_build_number(xcodeproj: xcodeproj)
    "#{marketing_version}.#{build_number}"
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    ensure_git_status_clean
    increment_build
    commit_version_bump

    badge(shield: "Version-#{app_version}-red", shield_no_resize: true)

    gym(workspace: workspace, scheme: scheme)
    changelog = prompt_for_changelog
    pilot(changelog: changelog, distribute_external: true)
    git_commit(file: 'changelog.txt', message: 'Updated changelog.txt')

    reset_git_repo(files: app_icon_files)
    add_git_tag
    push_git_tags
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    gym(workspace: workspace, scheme: scheme)
    deliver(force: true)
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end

  lane :snapshots do
    snapshot
  end
end

def app_icon_files
  Dir['../FiveCalls/FiveCalls/Assets.xcassets/AppIcon.appiconset/*.png']
end

def prompt_for_release_notes
    `open changelog.txt -W`
    File.read('changelog.txt')
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
