
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# update_fastlane

default_platform :ios

xcodeproj = 'FiveCalls/FiveCalls.xcodeproj'
scheme = 'FiveCalls'

platform :ios do
  before_all do
    before_all do
      setup_circle_ci
    end
  end

  desc "Runs all the tests"
  lane :test do
    scan(project: xcodeproj, scheme: scheme, xcargs: "-skipPackagePluginValidation")
    xcov(project: "FiveCalls/FiveCalls.xcodeproj",
    scheme: "FiveCalls",
    minimum_coverage_percentage: 30.0)
  end

  desc "Runs code coverage"
  lane :coverage do
    clear_derived_data(derived_data_path: "xcov_output")
    xcov(project: "FiveCalls/FiveCalls.xcodeproj",
    scheme: "FiveCalls",
    minimum_coverage_percentage: 24.0,
    output_directory: "xcov_output")
  end

  desc "Increments build number"
  lane :increment_build do
    increment_build_number(xcodeproj: xcodeproj)
  end

  lane :app_version do
    get_app_version(xcodeproj: xcodeproj)
  end

  def get_app_version(xcodeproj:)
    marketing_version = get_version_number(xcodeproj: xcodeproj)
    build_number = get_build_number(xcodeproj: xcodeproj)
    "#{marketing_version}.#{build_number}"
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    ensure_git_status_clean
    increment_build
    commit_version_bump(xcodeproj: xcodeproj)

    gym(project: xcodeproj, scheme: scheme)
    changelog = prompt_for_release_notes
    pilot(changelog: changelog)
    git_commit(path: 'fastlane/changelog.txt', message: 'Updated changelog.txt')

    reset_git_repo(files: app_icon_files)
    add_git_tag
    push_git_tags
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    ensure_git_status_clean
    increment_build
    commit_version_bump

    gym(project: xcodeproj,
        scheme: scheme,
        export_xcargs: "-allowProvisioningUpdates")
    deliver(force: true)

    add_git_tag
    push_git_tags
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end

  lane :snapshots do
    snapshot
  end
end

def app_icon_files
  Dir['../FiveCalls/FiveCalls/Assets.xcassets/AppIcon.appiconset/*.png']
end

def prompt_for_release_notes
    puts "Opening changelog.txt. Edit it and quit the editor to continue."
    `open changelog.txt -W`
    File.read('changelog.txt')
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
