devices([
  # "iPhone SE (3rd generation)",
  "iPhone 15",
  # "iPhone 15 Pro",
  # "iPhone 15 Pro Max",
  # "iPad Pro (12.9-inch) (6th generation)"
])

languages([
  "en-US",
])

project "./FiveCalls/FiveCalls.xcodeproj"
scheme "FiveCallsUITests"

output_directory "./screenshots"
clear_previous_screenshots true

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch-arguments
launch_arguments(["-hasShownWelcomeScreen false"])

# For more information about all available options run
# fastlane snapshot --help
