devices([
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone 11",
  "iPhone 11 Pro",
  "iPhone 11 Pro Max",
  "iPad Pro (12.9-inch) (3rd generation)"
])

languages([
  "en-US",
])

workspace "./FiveCalls/FiveCalls.xcworkspace"
scheme "FiveCallsUITests"

output_directory "./screenshots"
clear_previous_screenshots true

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch-arguments
launch_arguments(["-hasShownWelcomeScreen false"])

# For more information about all available options run
# fastlane snapshot --help
