name: FiveCalls

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Test
        uses: actions/checkout@v1
      - name: Build and Test
        run:  xcodebuild test -project FiveCalls.xcodeproj -scheme FiveCalls -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' build test
